# Generated by Django 4.2.15 on 2024-10-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article", name="count", field=models.IntegerField(default=0),
        ),
    ]
