"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

import yaml 
import pymysql

pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#f1g*l$w@uq9=4!k*zl*f-nhizhtnta)bg_*ifl#86l!qu*^4*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if os.getenv("GAE_APPLICATION",None):
    ALLOWED_HOSTS = ["blog-site-reallysite.an.r.appspot.com",]
    pass
else:
    ALLOWED_HOSTS=['*']
    DEBUG = True




if DEBUG:
    with open(os.path.join(BASE_DIR,'secrets','secret_dev.yaml')) as file:
        objs = yaml.safe_load(file)
        for obj in objs:
            os.environ[obj] = objs[obj]
else:
    #本番環境の場合
    pass



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "livereload",#livereload
    "django.contrib.staticfiles",
    "mysite",
    "blog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "livereload.middleware.LiveReloadScript",
]

LIVERELOAD_PORT = 8080

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR,"templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv("GAE_APPLICATION",None):
    DATABASES ={
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USERNAME"),
            "PASSWORD": os.getenv("DB_USERPASS"),
            "HOST": "/cloudsql/{}".format(os.getenv("DB_CONNECTION")),
        }
    }
else:
    DATABASES ={
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USERNAME"),
            "PASSWORD": os.getenv("DB_USERPASS"),
            "HOST": "127.0.0.1",
            "PORT": "3306",
        }
    }

    # DATABASES = {
    #     "default": {
    #         "ENGINE": "django.db.backends.sqlite3",
    #         "NAME": BASE_DIR / "db.sqlite3",
    #     }
    # }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# --- static 設定項目 ---
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static"),
]
# --- static 設定項目 ---

STATIC_ROOT = os.path.join(BASE_DIR,"staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL="mysite.User" #mysiteディレクトリで作成したUserを指定

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"

LOGOUT_URL = "/logout"
LOGOUT_REDIRECT_URL = "/login"

from django.contrib import messages

MESSAGE_TAGS={
    messages.ERROR: "rounded-0 alert alert-danger",
    messages.WARNING: "rounded-0 alert alert-warning",
    messages.SUCCESS: "rounded-0 alert alert-success",
    messages.INFO: "rounded-0 alert alert^info",
    messages.DEBUG: "rounded-0 alert alert-sedondary",
}


# --- Configuration for sending email ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" ## メールバックエンドの指定
EMAIL_HOST = "smtp.gmail.com" ## メールサーバーの指定
EMAIL_PORT = 587 ## メールサーバーのポート番号
EMAIL_USE_TLS = True ## TLSの使用
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER") ## メールアドレス
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD") ## メールパスワード


MEDIA_ROOT = BASE_DIR